from .index import bp as index
from .proxy import bp as proxy
from .vanity import bp as vanity
from .artworks import bp as artworks
from .login import bp as login
from .search import bp as search
from .upload import bp as upload
from .discovery import bp as discovery
from .users import bp as users
from .user_action import bp as user_action
from .profile_edit import bp as profile_edit