services:
  vixipy:
    container_name: vixipy
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      #PYXIV_TOKEN: ""
      #PYXIV_TOKEN_BALANCER: "random"
      PYXIV_PORT: 8000
      PYXIV_NOR18: 0
      PYXIV_LIMITING: 0
      #PYXIV_ACCEPTLANG: ""
      #PYXIV_INSTANCENAME: ""
      #PYXIV_ACQUIRE_SESSION: 0
      #PYXIV_DEFAULT_PROXY: ""
      #PYXIV_DEFAULT_THEME: ""
      #PYXIV_ADDITIONAL_THEMES: ""
      PYXIV_WORKERS: 5
