services:
  vixipy:
    container_name: vixipy
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      VIXIPY_PORT: 8000
      VIXIPY_WORKERS: 1
      VIXIPY_INSTANCE_NAME: "My awesome Vixipy instance"

      # by default, logging is enabled, but you can disable it like this
      #VIXIPY_LOG_HTTP: "0"
      #VIXIPY_LOG_PIXIV: "0"

      # disable r18 works viewing
      #VIXIPY_NO_R18: "1"

      # try this if you have issues connecting to cloudflare
      #VIXIPY_PIXIV_DIRECT_CONNECTION: "1"

      # getting attacked by bots? ratelimiting can slow them down
      #VIXIPY_QUART_RATE_LIMITER_ENABLED: "1"
      #VIXIPY_BEHIND_REVERSE_PROXY: "1" # only enable this if you are behind reverse proxy (caddy, nginx, etc)

      # caching can speed up your instance, but will require memcached
      #VIXIPY_CACHE_PIXIV_REQUESTS: "1"
      #VIXIPY_CACHE_TTL: "300"

      # Uncomment this line if using caching or ratelimiting
      #VIXIPY_MEMCACHED_HOST: "memcached"
  
  # You must have memcached running to use caching/ratelimiting. Configure it to your liking
  #memcached:
  #  image: memcached
  #  restart: unless-stopped
  #  command:
  #    - --max-item-size=4m
  #    - --conn-limit=1024
  #    - --memory-limit=128
  #    - --threads=1